version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
    networks:
      - clipboard-network
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - clipboard-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "8099:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../src/static:/usr/share/nginx/html/static
    environment:
      - TZ=Asia/Shanghai
    networks:
      - clipboard-network
    restart: always
    depends_on:
      - web

networks:
  clipboard-network:
    driver: bridge

volumes:
  redis_data:
